-- Create the database
CREATE DATABASE IF NOT EXISTS alx_book_store;

-- Use the database
USE alx_book_store;

-- 1. AUTHORS TABLE
CREATE TABLE AUTHORS (
    AUTHOR_ID INT NOT NULL AUTO_INCREMENT,
    AUTHOR_NAME VARCHAR(215) NOT NULL,
    PRIMARY KEY (AUTHOR_ID)
) ENGINE = INNODB;

-- 2. CUSTOMERS TABLE
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INT NOT NULL AUTO_INCREMENT,
    CUSTOMER_NAME VARCHAR(215) NOT NULL,
    EMAIL VARCHAR(215) NOT NULL,
    ADDRESS TEXT,
    PRIMARY KEY (CUSTOMER_ID)
) ENGINE = INNODB;

-- 3. BOOKS TABLE
CREATE TABLE BOOKS (
    BOOK_ID INT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(130) NOT NULL,
    AUTHOR_ID INT NOT NULL,
    PRICE DOUBLE NOT NULL,
    PUBLICATION_DATE DATE,
    PRIMARY KEY (BOOK_ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
) ENGINE = INNODB;

-- 4. ORDERS TABLE
CREATE TABLE ORDERS (
    ORDER_ID INT NOT NULL AUTO_INCREMENT,
    CUSTOMER_ID INT NOT NULL,
    ORDER_DATE DATE NOT NULL,
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
) ENGINE = INNODB;

-- 5. ORDER_DETAILS TABLE
CREATE TABLE ORDER_DETAILS (
    ORDERDETAILID INT NOT NULL AUTO_INCREMENT,
    ORDER_ID INT NOT NULL,
    BOOK_ID INT NOT NULL,
    QUANTITY DOUBLE NOT NULL,
    PRIMARY KEY (ORDERDETAILID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID)
) ENGINE = INNODB;
